
[brick]
	#A reverse multiplier to apply to the vertical support mass of the block[s].
	#Range: 0.0 ~ 1.0
	BeamStrength = 0.7

	#A list of block IDs to be affected by this definition.
	Blocks = ["minecraft:bricks", "minecraft:chiseled_nether_bricks", "minecraft:chiseled_stone_bricks", "minecraft:cracked_nether_bricks", "minecraft:cracked_polished_blackstone_bricks", "minecraft:cracked_stone_bricks", "minecraft:end_stone_bricks", "minecraft:infested_chiseled_stone_bricks", "minecraft:infested_cracked_stone_bricks", "minecraft:infested_mossy_stone_bricks", "minecraft:infested_stone_bricks", "minecraft:mossy_stone_bricks", "minecraft:nether_bricks", "minecraft:polished_blackstone_bricks", "minecraft:prismarine_bricks", "minecraft:quartz_bricks", "minecraft:red_nether_bricks", "minecraft:stone_bricks"]

	#The chance of the block[s] breaking after falling and landing.
	#Range: 0.0 ~ 1.0
	BreakChanceOnLanded = 0.2

	#Whether the block[s] should break instead of falling.
	BreakOnFalling = false

	#The minimum velocity, in meters per tick, the block[s] must land at before they have a chance of breaking.
	#Range: 0.0 ~ 1.7976931348623157E308
	BreakVelocityMinOnLanded = 0.5

	#The damage the block[s] will cause to entities after falling and landing on them.
	#Range: 0.0 ~ 1.7976931348623157E308
	EntityDamage = 2.0

	#Whether the block[s] should have a fake full-block collision box.
	FakeFullBlock = false

	#Whether the block[s] should be allowed to float on water.
	FloatsOnWater = false

	#Whether the block[s] should be allowed to horizontally attach to other blocks.
	IsAttachable = true

	#Whether the block[s] should be allowed to vertically attach to other blocks.
	IsHangable = true

	#The mass of the block[s], in kilograms.
	#Range: > 1
	Mass = 1800

	#Whether the block[s] will receive chunk updates.
	ReceivesChunkUpdates = true

	#Whether the block[s] will receive neighbouring block updates.
	ReceivesNeighbourUpdates = true

	#The chance of the block[s] sliding after falling and landing.
	#Range: 0.0 ~ 1.0
	SlideChanceOnLanded = 0.6

	#The chance of the block[s] sliding after being placed.
	#Range: 0.0 ~ 1.0
	SlideChanceOnPlaced = 0.0

	#The maximum mass the block[s] can support horizontally and vertically.
	#Range: > 0
	SupportMass = 14000

