
[Fabricators]

	#sand fabricator
	[Fabricators.sand_fabricator]
		#Maximum amount of FE that can be stored in the block
		#Range: > 0
		maxFE = 1000000
		#Maximum amount of FE that can be transferred into the block per tick
		#Range: > 0
		maxTransfer = 5000
		#Cost to create one sand per operation
		#Range: > 0
		operationCost = 50
		#Frequency (in ticks) that sand is produced
		#Range: > 0
		frequency = 25

	#red_sand fabricator
	[Fabricators.red_sand_fabricator]
		#Maximum amount of FE that can be stored in the block
		#Range: > 0
		maxFE = 1000000
		#Maximum amount of FE that can be transferred into the block per tick
		#Range: > 0
		maxTransfer = 5000
		#Cost to create one red_sand per operation
		#Range: > 0
		operationCost = 250
		#Frequency (in ticks) that red_sand is produced
		#Range: > 0
		frequency = 45

	#clay fabricator
	[Fabricators.clay_fabricator]
		#Maximum amount of FE that can be stored in the block
		#Range: > 0
		maxFE = 1000000
		#Maximum amount of FE that can be transferred into the block per tick
		#Range: > 0
		maxTransfer = 5000
		#Cost to create one clay per operation
		#Range: > 0
		operationCost = 400
		#Frequency (in ticks) that clay is produced
		#Range: > 0
		frequency = 65

	#netherrack fabricator
	[Fabricators.netherrack_fabricator]
		#Maximum amount of FE that can be stored in the block
		#Range: > 0
		maxFE = 1000000
		#Maximum amount of FE that can be transferred into the block per tick
		#Range: > 0
		maxTransfer = 5000
		#Cost to create one netherrack per operation
		#Range: > 0
		operationCost = 50
		#Frequency (in ticks) that netherrack is produced
		#Range: > 0
		frequency = 25

	#soul_sand fabricator
	[Fabricators.soul_sand_fabricator]
		#Maximum amount of FE that can be stored in the block
		#Range: > 0
		maxFE = 1000000
		#Maximum amount of FE that can be transferred into the block per tick
		#Range: > 0
		maxTransfer = 5000
		#Cost to create one soul_sand per operation
		#Range: > 0
		operationCost = 400
		#Frequency (in ticks) that soul_sand is produced
		#Range: > 0
		frequency = 120

	#slime fabricator
	[Fabricators.slime_fabricator]
		#Maximum amount of FE that can be stored in the block
		#Range: > 0
		maxFE = 1000000
		#Maximum amount of FE that can be transferred into the block per tick
		#Range: > 0
		maxTransfer = 5000
		#Cost to create one slime per operation
		#Range: > 0
		operationCost = 500
		#Frequency (in ticks) that slime is produced
		#Range: > 0
		frequency = 70

	#ice fabricator
	[Fabricators.ice_fabricator]
		#Maximum amount of FE that can be stored in the block
		#Range: > 0
		maxFE = 1000000
		#Maximum amount of FE that can be transferred into the block per tick
		#Range: > 0
		maxTransfer = 5000
		#Cost to create one ice per operation
		#Range: > 0
		operationCost = 250
		#Frequency (in ticks) that ice is produced
		#Range: > 0
		frequency = 95

	#snow fabricator
	[Fabricators.snow_fabricator]
		#Maximum amount of FE that can be stored in the block
		#Range: > 0
		maxFE = 1000000
		#Maximum amount of FE that can be transferred into the block per tick
		#Range: > 0
		maxTransfer = 5000
		#Cost to create one snow per operation
		#Range: > 0
		operationCost = 250
		#Frequency (in ticks) that snow is produced
		#Range: > 0
		frequency = 95

	#dirt fabricator
	[Fabricators.dirt_fabricator]
		#Maximum amount of FE that can be stored in the block
		#Range: > 0
		maxFE = 1000000
		#Maximum amount of FE that can be transferred into the block per tick
		#Range: > 0
		maxTransfer = 5000
		#Cost to create one dirt per operation
		#Range: > 0
		operationCost = 50
		#Frequency (in ticks) that dirt is produced
		#Range: > 0
		frequency = 25

	#gravel fabricator
	[Fabricators.gravel_fabricator]
		#Maximum amount of FE that can be stored in the block
		#Range: > 0
		maxFE = 1000000
		#Maximum amount of FE that can be transferred into the block per tick
		#Range: > 0
		maxTransfer = 5000
		#Cost to create one gravel per operation
		#Range: > 0
		operationCost = 50
		#Frequency (in ticks) that gravel is produced
		#Range: > 0
		frequency = 25

	#end_stone fabricator
	[Fabricators.end_stone_fabricator]
		#Maximum amount of FE that can be stored in the block
		#Range: > 0
		maxFE = 1000000
		#Maximum amount of FE that can be transferred into the block per tick
		#Range: > 0
		maxTransfer = 5000
		#Cost to create one end_stone per operation
		#Range: > 0
		operationCost = 100
		#Frequency (in ticks) that end_stone is produced
		#Range: > 0
		frequency = 25

